### ISSUE TITLE
Error when trying to run on Mac

### ISSUE THREAD

**Issue by wornish** [vyskocil/Polaris#1]
I have tried to use this and have run into a problem.

I am on a Mac and running MacOS Sonoma 14.4.1
I have updated Python to the latest version 3.12.34
I have installed astropy using pip3
I have downloaded your script. polaris_stellarium.py
I have edited the script to show my correct latitude and longitude.

When I run the script I get this error message
SyntaxWarning: invalid escape sequence '\d'
polaris_msg_re = re.compile('^(\d\d\d)@([^#]*)#')
Failed to connect to server: [Errno 60] Connect call failed ('192.168.0.1', 9090)
Any suggestions?

**Comment by vyskocil** [comment]
It seems that the SyntaxWarning is coming from the new Python 3.12.34 version but it should not prevent the script to run. But may you try to change the '     ' in "      " and look if there is still this warning ? 

Did you connect the mobile app to the Polaris first, then setup the astro mode and leave the mobile app connected ?
Then you should connect the Mac to the Polaris WIFI and try the script again.

**Comment by wornish** [comment]
Thanks you for the quick reply. 
I wasn't fully setting up the polaris mount to be tracking before starting the script. The script is now working and communicating with the mount. I now have a problem in getting Stellarium to add a new telescope but I will work on that.

**Comment by wornish** [comment]
Update 2. I was using an old version of Stellarium, I updated it and everything now works. It's brilliant. Just need the clouds to clear tonight and I will give it a full test.   Thank you for sharing this.

**Comment by vyskocil** [comment]
Thank you @wornish for the report it helped to clarify the documentation.
